Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

   config.vm.provision "shell", inline: <<-SHELL

   # Remove namespace if it exists.
    sudo ip netns del ns1 &>/dev/null

    # 1. Create namespace
    sudo ip netns add ns1

    # 2. Create veth link.
    ip link add v-eth1 type veth peer name v-peer1

    # 3. Add peer-1 to NS.
    ip link set v-peer1 netns ns1

    # 4.A. Setup IP address of v-eth1.
    ip addr add 10.200.1.1/24 dev v-eth1
    ip link set v-eth1 up

    # 4.B. Setup IP address of v-peer1.
    ip netns exec ns1 ip addr add 10.200.1.2/24 dev v-peer1
    ip netns exec ns1 ip link set v-peer1 up
    # brought up the loopback interface inside ns1 as well..
    ip netns exec ns1 ip link set lo up

    # 5. make all external traffic leaving ns1 to go through v-eth1.
    ip netns exec ns1 ip route add default via 10.200.1.1


    # 6. Share internet access between host and NS.
    # 6.1 Enable IP-forwarding.
    echo 1 > /proc/sys/net/ipv4/ip_forward

    # 6.2 Flush forward rules, policy DROP by default.
    iptables -P FORWARD DROP
    iptables -F FORWARD

    # 6.3 Flush nat rules.
    iptables -t nat -F

    # 6.4 Enable masquerading of 10.200.1.0.
    iptables -t nat -A POSTROUTING -s 10.200.1.0/255.255.255.0 -o eth0 -j MASQUERADE

    # 6.5 Allow forwarding between eth0 and v-eth1.
    iptables -A FORWARD -i eth0 -o v-eth1 -j ACCEPT
    iptables -A FORWARD -o eth0 -i v-eth1 -j ACCEPT

   SHELL
end
